[theme]
backgroundColor = "#2d1b3d"        # Deep muted purple
primaryColor = "#9b7eba"           # Soft dusty purple for accents
secondaryBackgroundColor = "#3d2952"  # Slightly lighter muted purple
textColor = "#e8e3ed"              # Soft off-white for better readability
font = "sans serif"